api-url: {{ accounting_api_url }}
api-token: {{ accounting_api_token }}
metal-api-url: {{ accounting_metal_api_url }}
metal-api-hmac: {{ accounting_metal_api_hmac }}
masterdata-api-hostname: {{ accounting_masterdata_api_hostname }}
masterdata-api-port: {{ accounting_masterdata_api_port }}
masterdata-api-hmac: {{ accounting_masterdata_api_hmac }}
stripe-account-token: {{ accounting_stripe_private_token }}
nsqd-addr: {{ accounting_nsqd_address }}
log-level: {{ accounting_log_level }}
activated-migration: {{ accounting_activated_migration | lower }}
